<?xml version="1.0"?>
<robot name="diff_drive" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find diff_drive_description)/urdf/diff_drive.gazebo" />
<xacro:include filename="$(find diff_drive_description)/urdf/materials.xacro" />
<xacro:include filename="$(find diff_drive_description)/urdf/macros.xacro" />

<xacro:property name="PI" value="3.1415926535897931"/>

<xacro:property name="chassisHeight" value="0.1"/>
<xacro:property name="chassisLength" value="0.4"/>
<xacro:property name="chassisWidth" value="0.2"/>
<xacro:property name="chassisMass" value="50"/>

<xacro:property name="casterRadius" value="0.05"/>
<xacro:property name="casterMass" value="5"/>

<xacro:property name="wheelWidth" value="0.05"/>
<xacro:property name="wheelRadius" value="0.1"/>
<xacro:property name="wheelPos" value="${wheelRadius}"/>
<xacro:property name="wheelMass" value="5"/>

<xacro:property name="laserHeight" value="0.1"/>
<xacro:property name="laserRadius" value="0.05"/>
<xacro:property name="laserMass" value="0.1"/>


<!-- base joint -->
<link name="base_link"/>

<joint name="base_joint" type="fixed">
	<parent link="base_link"/>
	<child link="chassis"/>
</joint>


<!-- chassis -->
<link name="chassis">
<collision> 
	<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
	<geometry> 
		<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
	</geometry> 
</collision>
<visual> 
	<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
	<geometry> 
		<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/> 
	</geometry> 
	<material name="orange"/>
</visual>
<inertial> 
	<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/> 
	<mass value="${chassisMass}"/> 
	<box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
</inertial>
</link>


<!-- caster wheel -->
<joint name="fixed" type="fixed">
  <parent link="chassis"/>
  <child link="caster_wheel"/>
</joint>

<link name="caster_wheel">
  <collision>
    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
  </collision>
  
  <visual>
    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${casterRadius}"/>
    </geometry>
    <material name="red"/>
  </visual>

  <inertial>
    <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
    <mass value="${casterMass}"/>
    <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
  </inertial>
</link>


<!-- main wheels -->
<wheel lr="left" tY="1"/>
<wheel lr="right" tY="-1"/> 	

<!-- laser sensor -->
<link name="hokuyo_link">
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="${laserRadius}" length="${laserHeight}"/>
		</geometry>
	</collision>
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="${laserRadius}" length="${laserHeight}"/>
		</geometry>
		<material name="white"/>
	</visual>
	<inertial> 
		<origin xyz="0 0 0" rpy="0 0 0"/> 
		<mass value="${laserMass}"/> 
		<cylinder_inertia m="${laserMass}" r="${laserRadius}" h="${laserHeight}"/>
	</inertial>
</link>

<joint name="hokuyo_joint" type="fixed">
	<axis xyz="0 1 0"/>
	<origin xyz="${casterRadius-chassisLength/2} 0 ${chassisHeight+wheelRadius}" rpy="0 0 ${PI}"/> 
	<parent link="base_link"/>
	<child link="hokuyo_link"/>
</joint>

</robot>
